New custom model
RootKit-Org/AI-Aimbot pull request #123
Opened 2023-11-06 20:23 UTC by FeelsDaumenMan

2023-11-06 20:31 UTC, FeelsDaumenMan commented
Rename exampleUsername to Fortnite

2023-11-06 23:05 UTC, Qfc9 requested changes
Needs to be in a new folder. Not the example folder.

2023-11-07 06:19 UTC, FeelsDaumenMan commented
Updated

2023-11-07 17:07 UTC, Qfc9 approved these changes

2023-11-07 17:08 UTC, merged